import = [
	"~/.config/alacritty/themes/themes/dark_pastels.toml"
]

[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 18 

[cursor]
style = { shape = "Block", blinking = "Always" }
