####################
### WINDOW RULES ###
####################

# General rule for all windows
windowrule = suppress_event maximize, match:class .*

# BROWSER
# windowrule = opacity 0.90 0.90, match:class ^($browser)$
windowrule = workspace 1, match:class ^($browser)$

# TERMINAL
windowrule = workspace 2, match:class ^($terminal)$

# MENU
windowrule = opacity 0.10 0.10, match:class ^($menu)$

# DRAWING
windowrule = workspace 4, match:class ^($drawing)$

# MUSIC
windowrule = workspace 11, match:class ^($music)$

# DISCORD
windowrule = workspace 12, match:class ^(discord)$

# STEAM (silent rules use the following syntax)
windowrule = workspace 13 silent, match:class ^steam$
